import React, { Component } from "react";
import { Link } from "react-router-dom";


class Privacy extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <React.Fragment>
          <div style = {{margin: 70}}>
          <Link style = {{marginBottom: 30}} to="/" className=" btn mr-3 video-play-icon " onClick={this.openModal}><i className="mdi mdi-arrow-left mr-2"></i> Vovler a inicio</Link>
          <h3 className="title-heading mt-4">Aviso de privacidad de Aldel</h3>
          
            <p>
                Bienvenido a la Política de privacidad de Aldel. Esta Política de privacidad se aplica a usted si es miembro, experto u otro visitante de la plataforma de Aldel ("Plataforma de Aldel") disponible en www.aldel.io ("Sitio Web de Aldel") y en otros sitios web de terceros. Los miembros, expertos y todos los demás visitantes del sitio de servicios de Aldel y / o la plataforma de servicios expertos de A se denominan en esta política "usted" o un "visitante de servicios”. Esta Política de privacidad se aplica independientemente de si está utilizando una computadora, un dispositivo móvil u otro dispositivo para visitar el sitio de servicios de la plataforma de Aldel.
                Se le considera un "Usuario" si se registra con la opción “Soy cliente” en la Plataforma de Aldel y se acepta su solicitud de usuario. Se le considera un "Consultor" si realiza su registro con la opción “Soy consultor” en la Plataforma Aldel y Aldel ha activado su perfil. Tenga en cuenta que esta Política de privacidad se aplica a todos los Visitantes de la Plataforma de Aldel, independientemente de si dicho visitante es un Usuario o un Consultor.	

                Esta Política de privacidad explica cómo Aldel y ciertos terceros pueden recopilar, usar y divulgar "Información personal" y otra información que obtenemos a través del Sitio de Aldel y a través de la Plataforma Aldel (en conjunto, "Datos").

                Definición de información personal.  Aldel considera que "Información personal" incluye información que, sola o en combinación con otra información, puede usarse para identificarlo o contactarlo fácilmente, como: nombre, dirección, dirección de correo electrónico o número de teléfono. Aldel no considera que la Información personal incluya información que ha sido anonimizada para que no permita que un tercero identifique fácilmente a un individuo específico.
                Uso y aceptación. Al utilizar el sitio web de Aldel o la plataforma de Aldel, usted acepta esta Política de privacidad. Si no acepta esta Política de privacidad, no debe utilizar el sitio web de Aldel  ni la plataforma de Aldel.
                Nuevos usos de la información personal y otra información. De vez en cuando, Aldel puede usar los Datos para usos nuevos e imprevistos que no se han divulgado previamente en nuestra Política de privacidad. Si nuestras prácticas de información cambian con respecto a la información recopilada anteriormente, Aldel hará los esfuerzos razonables para notificar y obtener el consentimiento para cualquier uso que pueda ser requerido por la ley.

                ¿Qué información se recopila de los visitantes de servicios expertos y cómo se recopila?
                Comunicaciones con consultores y Usuarios. Si participa en una comunicación con un Consultor o un Usuario utilizando el chat, nota de voz, llamada, video llamadas, imágenes, videos u otros productos o servicios de comunicación de Aldel puestos a su disposición por Aldel a través del Sitio web de Aldel o la Plataforma de Aldel puede proporcionar voluntariamente, o ser que se le solicite que proporcione información personal como su nombre, información de contacto y otra información para facilitar el servicio. Al proporcionar información personal y otra información a través de los productos o servicios de comunicación de Aldel, usted da su consentimiento para que Aldel recopile y procese dicha información para los fines descritos en esta Política de privacidad.
                Aldel mantiene transcripciones ("Transcripciones") de chats, llamadas, videollamadas, imágenes, videos, correos electrónicos y otras realizadas entre usted y cualquier Consultor o Usuario que utilice los productos y servicios de Aldel. Aldel puede, de acuerdo con la ley aplicable (incluidas las leyes relacionadas con el aviso y / o consentimiento), registrar y mantener grabaciones de comunicaciones de voz ("Grabaciones") entre usted y cualquier Consultor o Usuario.
                Comunicaciones con Aldel. Si participa en una comunicación con Aldel relacionada con la Plataforma de Aldel o el Sitio web de Aldel utilizando el chat, notas de voz, llamadas, videollamadas correo electrónico, voz u otros productos o servicios de comunicación de Aldel puestos a su disposición por Aldel,  puede proporcionar voluntariamente, o se le puede solicitar que proporcione, Información personal como su nombre, información de contacto y otra información para facilitar el servicio. Al proporcionar información personal y otra información a través de los productos o servicios de comunicación de Aldel, usted da su consentimiento para que Aldel recopile y procese dicha información para los fines descritos en esta Política de privacidad.
                Aldel mantiene transcripciones de las comunicaciones que se llevan a cabo entre usted y Aldel. Aldel  también mantiene copias de Encuestas y Aldel puede, de acuerdo con la ley aplicable (incluidas las leyes relacionadas con el aviso y / o consentimiento), grabar y mantener  Grabaciones de las comunicaciones de voz entre el usuario y Aldel.

                Información del navegador e información de uso. Registramos la información del navegador web (por ejemplo, direcciones de protocolo de Internet y tipos de navegador) y otra información de uso del sitio web de Aldel y la plataforma de Aldel, como el recuento de visitas a la página, el tiempo dedicado a cada página, información de ubicación geográfica, información de navegación de la página, la información de búsqueda de navegación y la información del sistema operativo. Si el Visitante de Servicios utiliza un dispositivo móvil u otro dispositivo portátil para visitar o acceder al Sitio web de Aldel o la Plataforma de Aldel, podemos recopilar información de hardware relacionada con el dispositivo utilizado por el Visitante de Servicios. Su navegador puede estar configurado para limitar o evitar que se transmita la información del navegador descrita anteriormente. Si es así, el sitio web de Aldel, la plataforma de Aldel o ciertas herramientas de comunicación, u otras características o funciones ofrecidas como parte del sitio de web de Aldel o la plataforma de Aldel, pueden no estar disponibles para usted.
                Cuenta de usuario. Para que un visitante utilice muchas de las funciones u ofertas del sitio web de Aldel o de la plataforma de Aldel, es posible que el visitante deba abrir una cuenta de usuario y proporcionar información personal. Muchos servicios requieren el pago de una tarifa que determina el Consultor. Antes de utilizar los servicios de pago, el usuario deberá proporcionar información de pago a través de la cuenta de usuario. Aldel utiliza un procesador de tarjetas de crédito de terceros o tarjeta de debito para procesar y almacenar la información de la tarjeta de crédito o tarjeta de débito enviada a través de la cuenta del usuario.
                Aldel puede permitir que los Visitantes de Servicios inicien sesión en la Plataforma de Servicios Aldel y / o se inscriban como Usuario utilizando las credenciales de inicio de sesión utilizadas por dicho visitante en un sitio web de redes sociales de terceros (por ejemplo, Facebook, Google). Al iniciar sesión o inscribirse utilizando las credenciales del sitio web de terceros, el Visitante de Servicios  da su consentimiento para que Aldel recopile y mantenga la información proporcionada a través de dicho sitio web de terceros. Aldel no es responsable de las prácticas de privacidad de ningún sitio web de terceros.

                Solicitudes de información, noticias y otro contenido. 
                Cuando se registra para convertirse en Usuario o Consultor, puede registrarse para recibir información, noticias y otro contenido relacionado con productos y servicios nuevos y existentes relacionados con el sitio web de Aldel, la Plataforma de Aldel y eventos y otra información relacionada con Aldel que puede ser de tu interés. También puede registrarse para recibir información, noticias y otro contenido de terceros cuyos servicios y / o productos creemos que pueden ser de su interés. Se le pedirá que proporcione información personal, como detalles de contacto y otra información, relevante para entregar dichas noticias e información. Mantenemos toda esa información.

                Solicitudes de soporte técnico. Si necesita asistencia técnica relacionada con el sitio web de Aldel o la plataforma de Aldel, deberá completar un formulario con el fin de definir y aclarar su solicitud de asistencia técnica. Al enviar una solicitud de asistencia técnica, se le pedirá que proporcione información personal, incluida una dirección de correo electrónico y una descripción del problema. Mantenemos copias de todas las solicitudes de soporte técnico y otra información enviada con o relacionada con dichas solicitudes.
                Promociones. De vez en cuando, podemos ofrecer promociones en el sitio web de Aldel o a través de la plataforma Aldel. Si lo hacemos, y si desea participar, es posible que deba proporcionar información personal, como información de contacto y otra información. Mantenemos dicha información.
                Solicitantes de servicios expertos. Si un visitante desea postularse para ser un experto en la plataforma Aldel, se le pedirá al visitante que envíe la información personal que se le solicite, al seleccionar la opción “Soy consultor” al momento de registro de cuenta. Aldel, así como terceros afiliados y otros terceros, pueden mantener cualquier información proporcionada por o en nombre de un visitante con el fin de convertirse en un experto. Tenga en cuenta que Aldel puede tener términos de privacidad adicionales que se aplican a los solicitantes expertos. Dichos términos estarán disponibles cuando un solicitante solicite ser un experto o cuando un solicitante acceda a su cuenta.

                Cookies. Los servicios de Aldel utilizan cookies y otras tecnologías similares, como etiquetas de píxeles, para recopilar y almacenar información que se genera automáticamente a medida que utiliza los servicios, incluidas sus preferencias y estadísticas de uso anónimas.

                Nuestros socios utilizan cookies similares y otras tecnologías, que también pueden incluir cookies Flash. Las cookies de Flash se establecen a través de un mecanismo en Adobe Flash Player. Con las cookies de Flash, sus datos se almacenan en varios lugares y pueden restaurarse una vez que los elimine. Para controlar las cookies flash, modifique la configuración en el sitio web de Macromedia aquí. HTML5 tiene una función de almacenamiento local que, cuando se utiliza, permite un acceso más rápido a un sitio web en una nueva visita. Actualmente, algunos dispositivos móviles y navegadores de escritorio admiten HTML5. Los datos HTML5 no se almacenan en el archivo de "cookies" de un navegador. La mayoría de los navegadores también le brindan la capacidad de controlar las cookies, generalmente a través del menú de configuración; la función de ayuda de su navegador le explicará cómo. Además, algunos de nuestros socios le permiten optar por no usar cookies haciendo clic aquí. Las elecciones que realiza en estos sitios son específicas del navegador. Por lo tanto, si usa un navegador diferente, deberá volver a optar por no participar. Si un navegador está configurado para rechazar las cookies, es posible que algunas de las funciones ofrecidas por Aldel no estén disponibles o no funcionen con la misma eficacia para usted.

                ¿Cómo utiliza y divulga Aldel la información que recopila de los usuarios de Aldel?
                Transcripciones, encuestas y grabaciones. Aldel puede acceder y utilizar Transcripciones, Encuestas y Grabaciones con el propósito de realizar o entregar un servicio a un Visitante de Servicios, brindar servicios de mantenimiento o soporte para un Visitante de Servicios, con fines de capacitación y garantía de calidad, con el propósito de investigar cualquier reclamo realizado por o relacionado con un Visitante de Servicios, con el fin de mejorar nuestros servicios y / o para otros fines legales. Los proveedores de servicios externos contratados por Aldel  para realizar servicios en nombre de Aldel también pueden tener acceso a transcripciones, encuestas y grabaciones con el fin de realizar o prestar un servicio a Aldel, proporcionar servicios de mantenimiento o soporte, con fines de capacitación y garantía de calidad, para con el fin de investigar cualquier reclamo realizado por un Visitante de Servicios o relacionado con el uso de los servicios por parte de un Visitante de Servicios, con el fin de mejorar nuestros servicios y / o para otros fines legales.
                Los Consultores con los que se comunica un Usuario u otro visitante de servicios tienen acceso a las transcripciones y grabaciones entre ellos. Aldel no tiene control sobre las prácticas de privacidad de dichos Consultores. Se le anima a verificar las prácticas de privacidad de los Expertos antes de comunicarse con ellos.

                Información de Navegador y Cookies. Utilizamos información del navegador, cookies y etiquetas de píxeles para determinar si un servicio de comunicación o material de marketing debe implementarse en su navegador cuando visita el sitio web de Aldel o utiliza la plataforma de Aldel. También podemos usar información del navegador, cookies y etiquetas de píxeles: para determinar cómo llegó al sitio web de Aldel la o a la plataforma de Aldel, para determinar si es un visitante que regresa, para ayudarnos a mejorar nuestras ofertas de productos y servicios, para garantizar la calidad. y con fines de capacitación, para ayudar a diagnosticar problemas con nuestros servidores, para recopilar información demográfica amplia, para administrar y optimizar nuestros servicios, para entregarle materiales de marketing u otros materiales en nombre de terceros y para otros fines legales. La información recopilada por los propios operadores externos se rige por sus propias políticas de privacidad.

                Información agregada. Podemos agregar información para que no sea Información personal, y podemos usar y compartir dicha información agregada con fines de capacitación y garantía de calidad, para brindar nuestros servicios, para expandir y mejorar nuestros servicios y para otros fines legales.
                Terceros. Aldel no vende, intercambia ni alquila la Información personal proporcionada por usted en ninguna Transcripción, Encuesta o Grabación para marketing directo o cualquier otro propósito, excepto según lo dispuesto en esta Política de Privacidad o con su permiso. Excepto como se describe en esta Política de privacidad, Aldel no divulga el contenido de las transcripciones, encuestas o grabaciones a terceros o proveedores que prestan servicios en nombre de Aldel.
                Si accedió al sitio web de Aldel o la plataforma de Aldel a través de un sitio web de terceros, puede estar sujeto a los términos y condiciones que se aplican a ese sitio web de terceros. Como se menciona a continuación, Aldel no es responsable de las prácticas de privacidad de ningún tercero.
                Aldel utiliza instalaciones de datos de terceros y otros proveedores de servicios de terceros para realizar servicios que son manejados habitualmente por dichos proveedores. Dichos proveedores pueden almacenar y, si corresponde, procesar información personal y no personal de acuerdo con el servicio que brindan. También podemos compartir datos de blogs y otros datos de información no personal similares con terceros. Por ejemplo, podemos compartir datos de tráfico del sitioweb con un tercero que analiza y publica encuestas de tráfico del sitio web.


                Razón legal para divulgar. Aldel puede divulgar su información, incluida la información personal, si: (i) Aldel cree razonablemente que la divulgación es necesaria para cumplir con un proceso legal (como una orden judicial, citación, orden de registro, etc.) u otro requisito legal de cualquier gobierno. autoridad, (ii) la divulgación mitigaría potencialmente nuestra responsabilidad en una demanda real o potencial, (iii) razonablemente necesaria para hacer cumplir esta Política de Privacidad, nuestros Términos de Uso o nuestro acuerdo con un Visitante de Servicios, (iv) la divulgación está destinada a ayudar investigar o prevenir transacciones no autorizadas u otras actividades ilegales (incluyendo cualquier reclamo de que un Usuario no autorizó los cargos incurridos a través de la Plataforma de Aldel o a través del Sitio web de Aldel), o (v) necesario o apropiado para proteger nuestros derechos o propiedad, o el derechos o propiedad de cualquier persona o entidad.

                Aviso especial para los usuarios de Aldel ubicados en países distintos al de los Estados Unidos Mexicanos.
                Si visita desde la Unión Europea u otras regiones con leyes que rigen la recopilación y el uso de datos que pueden diferir de las leyes de los Estados Unidos Mexicanos. Incluidas aquellas cuyas leyes de privacidad pueden ser más restrictivas que las leyes de los Estados Unidos Mexicanos. Tenga en cuenta que está transfiriendo sus datos personales a los Estados Unidos Mexicanos a Aldel. Al proporcionar sus datos personales, da su consentimiento para dicha transferencia.


                Tableros de mensajes, comunidades, blogs
                Si utiliza cualquier tablero de mensajes, comunidad (incluida cualquier comunidad o foro de servicios expertos) o blog disponible en el sitio web de Aldel o la plataforma de Aldel, debe tener en cuenta que cualquier información que envíe a través de esos servicios puede leerse, recopilarse y copiarse. y utilizado por otros usuarios, y podría utilizarse para enviarle mensajes no solicitados. Aldel puede acceder y utilizar dicha información con el propósito de realizar o brindar un servicio a un Visitante de Servicios, con el propósito de brindar servicios de mantenimiento o soporte, con fines de capacitación y garantía de calidad, con el propósito de investigar cualquier reclamo, con el propósito de mejorar nuestro servicios y / o para otros fines legales. Para evitar dudas, Aldel no es responsable de la información que elija enviar o publicar a través de cualquiera de esos servicios y Aldel no es responsable de cómo dicha información puede ser utilizada por otros o respondida por otros. Las obligaciones de privacidad de Aldel establecidas en esta Política de privacidad no se aplican a su uso de ningún tablero de mensajes, comunidad o blog en el sitio web de Aldel, en la plataforma de Aldel o en cualquier sitio web de terceros. Los términos adicionales disponibles a través de dicho tablero de mensajes, comunidad y / o blog pueden aplicarse a su uso de cualquiera de los anteriores.

                ¿Cómo protege Aldel su información?
                Seguridad. No se puede garantizar que las transmisiones de datos a través de Internet sean total y absolutamente seguras. Nuestro sitio web y nuestros servicios cuentan con medidas de seguridad diseñadas para proteger contra la pérdida, mal uso y alteración de la información bajo nuestro control. Nuestras medidas de seguridad incluyen las medidas que se describen a continuación.
                Cifrado y cortafuegos. Las transcripciones del chat se cifran durante la transmisión. Usamos el cifrado estándar Secure Socket Layer (SSL) que codifica la información para dichas transmisiones. Todas las transcripciones se mantienen y archivan en servidores seguros. El acceso a los datos almacenados está protegido por controles de seguridad de varios niveles que incluyen firewalls, controles de acceso basados ​​en roles y contraseñas. Los consultores y los usuarios pueden revisar su historial de chat y ver las transcripciones de los chats en los que han participado. Los consultores y los usuarios solo tienen acceso a los chats en los que participaron en su perfil de consultor o perfil de usuario. Los datos se respaldan con regularidad y los archivos se almacenan fuera del sitio en una ubicación segura.

                Términos adicionales que pueden aplicarse a su información


                La plataforma de Aldel está disponible en sitios web de terceros. La plataforma de Aldel puede estar disponible en sitios web de terceros. Además, los enlaces al sitio web de Aldel y la plataforma de Aldel pueden estar disponibles en sitios web de terceros. Aldel no es responsable ni controla las prácticas de privacidad de ningún tercero. En consecuencia, le recomendamos que revise las prácticas de privacidad de cada sitio web que utilice o visite.
                Transferencias comerciales. En el caso de que todos o sustancialmente todos los activos de Aldel hayan sido adquiridos, o en el caso de cualquier fusión, quiebra o reorganización que involucre a Aldel, todas las transcripciones, grabaciones y encuestas, así como cualquier otra información sobre usted y su uso de nuestros servicios. Probablemente se incluirá en los activos adquiridos o fusionados.
                Elección con respecto a la información personal. Si elige participar en cualquier comunicación utilizando nuestros servicios, depende de usted decidir qué información, si la hay, proporcionar durante dicha sesión. Dependiendo de su solicitud o de los medios de comunicación, es posible que no sea posible comunicarnos con usted o abordar todas sus preguntas sin proporcionar alguna información. Sin embargo, si no desea proporcionar cierta información, no debe hacerlo.
                Privacidad de los niños. Aldel no fomenta la participación o las visitas de los niños. Los visitantes que sean menores de 16 años tienen prohibido convertirse en miembros o expertos. Aldel no recopila a sabiendas información de identificación personal de niños menores de 16 años.

                Contactando a Aldel
                Aldel agradece sus comentarios sobre nuestra Política de privacidad. Envíe sus comentarios a santiagodlp65@gmail.com 

                Cambios a esta política de privacidad
                Le recomendamos que revise esta política periódicamente, ya que podemos actualizarla de vez en cuando. Su uso de cualquier servicio de Aldel ofrecido en el sitio web de Aldel o a través de la plataforma de Aldel después de un cambio en esta Política de privacidad representa su consentimiento a la nueva Política de privacidad en la mayor medida permitida por la ley.
            </p>
        </div>
      </React.Fragment>
    );
  }
}

export default Privacy;
